version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "david-sam-test-sept13"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ulbuoi2isaji"
s3_prefix = "david-sam-test-sept13"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
