AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3



Resources:
  TestGateway:
    Type: AWS::Serverless::HttpApi # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CorsConfiguration:
        AllowCredentials: true
        AllowMethods:
          - GET
          - PUT
          - POST
          - DELETE
          - PATCH
          - OPTIONS
        AllowOrigins: 
          - http://127.0.0.1:3000
        AllowHeaders:
          - Content-Type
          - Access-Control-Allow-Headers
          - Authorization
          - X-Requested-With
        ExposeHeaders:
          - Content-Length
          - Content-Range
      Domain:
        DomainName: sam.zero-david.xyz
        CertificateArn: arn:aws:acm:us-east-1:514226198018:certificate/e60cf2e7-a42e-4d48-bbeb-e0abf5309e7f
        EndpointConfiguration: REGIONAL
        # EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: Z005726678VSSXY2GMG9
      AccessLogSettings:
        DestinationArn: arn:aws:logs:us-east-1:514226198018:log-group:/aws/sam/stage/cheung0818
        Format: "$context.identity.sourceIp - - [$context.requestTime] \"$context.httpMethod $context.routeKey $context.protocol\" $context.status $context.responseLength $context.requestId $context.authorizer.error"

      Auth:
        DefaultAuthorizer: AuthorizerAuth0
        Authorizers:
          AuthorizerAuth0:
            FunctionArn: !GetAtt FunctionAuth0.Arn
            FunctionInvokeRole: !GetAtt GatewayInvokeAuthRole.Arn
            Identity:
              Headers:
              - Authorization
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
      # Auth:
      #   DefaultAuthorizer: JWT
      #   Authorizers:
      #     JWT:
      #       JwtConfiguration:
      #         issuer: "https://dev-l6w47akz.us.auth0.com/"
      #         audience:
      #           - https://sam.zero-david.xyz
      #       IdentitySource: "$request.header.Authorization"
  TestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        PublicAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref TestGateway
            Path: /status/{proxy+}
            Method: get
            Auth:
              Authorizer: NONE
        AuthenticateAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref TestGateway
            Path: /{proxy+}
            Method: get
  FunctionAuth0:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: auth0/
      Handler: index.handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          AUDIENCE: JQToEH9XFNRWw38prORSK1z6GXUMCRJS
          TOKEN_ISSUER: https://dev-l6w47akz.us.auth0.com/
          JWKS_URI: https://dev-l6w47akz.us.auth0.com/.well-known/jwks.json

  GatewayInvokeAuthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: api-gateway-invoke-auth-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: api-gateway-invoke-auth-lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource: "*"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TestApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${TestGateway}.execute-api.${AWS::Region}.amazonaws.com/hello"
  TestFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TestFunction.Arn
  TestFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TestFunctionRole.Arn
